### ISSUE TITLE
CLI installation not working

### ISSUE THREAD

**Issue by fredguth** [earthstar-project/earthstar-cli#20]
## What's the problem you want solved?
When trying to follow instructions from `https://earthstar-project.org/get-started/install-cli`, there is an error and the cli does not install.

command:
`deno install --allow-read --allow-write --allow-net --allow-run --allow-env --no-check --unstable -f --location https://earthstar-project.org -n earthstar https://deno.land/x/earthstar_cli/src/main.ts`

error:
`error: Module not found "https://deno.land/x/crayon/types.ts".
    at https://deno.land/x/crayon_chalk_aliases@1.1.0/index.ts:8:24
`

```
❯ deno --version
deno 1.23.1 (release, aarch64-apple-darwin)
v8 10.4.132.8
typescript 4.7.2
```

## Is there a solution you'd like to recommend?
🤷

**Comment by achou11** [comment]
@sgwilym just ran it and got this:

```sh
error: Module not found "https://deno.land/x/crayon/types.ts".
    at https://deno.land/x/crayon_chalk_aliases@1.1.0/index.ts:8:24
```

**Comment by fredguth** [comment]
same here.

**Comment by sgwilym** [comment]
Hey all, think I've finally solved this.

```
deno install --reload --allow-read --allow-write --allow-net --allow-run --allow-env --no-check --unstable -f --location https://earthstar-project.org -n earthstar https://deno.land/x/earthstar_cli/src/main.ts```

The issue was an older version of Earthstar being referenced in another file.

Thank you for your patience, and let me know if this really solves the issue for you.

**Comment by achou11** [comment]
@sgwilym worked for me! nice work

```sh
$ earthstar --version
v8.3.5
```

**Comment by fredguth** [comment]
```
❯ earthstar --version
v8.3.5
```
works for me too.
